### ISSUE TITLE
Update to 1.21.1

### ISSUE THREAD

**Issue by Fantomrat** [NikSneMC/Splashed#1]

**Comment by NikSneMC** [comment]
Isn't it working on 1.21.1?

**Comment by Fantomrat** [comment]
> Isn't it working on 1.21.1?

```
[19:52:58] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21.1 with any version between 1.21- (inclusive) and 1.21 (inclusive).
More details:
	 - Mod 'Splashed!' (splashed) 1.0 requires any version between 1.20.5 (inclusive) and 1.21 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
```

**Comment by NikSneMC** [comment]
> > Isn't it working on 1.21.1?
> 
> ```
> [19:52:58] [main/ERROR]: Incompatible mods found!
> net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
> A potential solution has been determined, this may resolve your problem:
> 	 - Replace 'Minecraft' (minecraft) 1.21.1 with any version between 1.21- (inclusive) and 1.21 (inclusive).
> More details:
> 	 - Mod 'Splashed!' (splashed) 1.0 requires any version between 1.20.5 (inclusive) and 1.21 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
> ```

That's because it's hardcoded in the jar. I'll upload an update

**Comment by NikSneMC** [comment]
What about this build? 
[Splashed!-1.0_1.20.5.jar.zip](https://github.com/user-attachments/files/17005918/Splashed.-1.0_1.20.5.jar.zip)

(remove .zip from the end)

**Comment by Fantomrat** [comment]
> What about this build? [Splashed!-1.0_1.20.5.jar.zip](https://github.com/user-attachments/files/17005918/Splashed.-1.0_1.20.5.jar.zip)
> 
> (remove .zip from the end)

Yeah, it works

**Comment by NikSneMC** [comment]
> > What about this build? [Splashed!-1.0_1.20.5.jar.zip](https://github.com/user-attachments/files/17005918/Splashed.-1.0_1.20.5.jar.zip)
> > (remove .zip from the end)
> 
> Yeah, it works

So, the only issue is hardcoded version. Closing the issue
